# Generated by Django 3.0.8 on 2020-07-17 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Blog',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('tag', models.CharField(choices=[('Burnout', 'Burnout'), ('Beginners', 'Beginners'), ('Frameworks', 'Frameworks'), ('Interviews', 'Interviews'), ('JavaScript', 'JavaScript'), ('Programming', 'Programming'), ('Python', 'Python'), ('Soft Skills', 'Soft Skills'), ('Tutorial Hell', 'Tutorial Hell')], max_length=100)),
                ('body', models.TextField(max_length=3000)),
                ('date_created', models.DateTimeField(auto_now_add=True, null=True)),
                ('date_updated', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
