# Generated by Django 3.0.8 on 2020-07-17 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0003_writer'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writer',
            old_name='blog_written',
            new_name='tag',
        ),
    ]
