# Generated by Django 3.0.8 on 2020-07-17 14:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('portfolio', '0004_auto_20200717_2015'),
    ]

    operations = [
        migrations.RenameField(
            model_name='writer',
            old_name='tag',
            new_name='blog_written',
        ),
        migrations.AlterField(
            model_name='writer',
            name='writer',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
