# Generated by Django 3.0.8 on 2020-07-17 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0012_blog_author'),
        ('portfolio', '0006_auto_20200717_2019'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='blog_written',
        ),
        migrations.AddField(
            model_name='writer',
            name='blog_written',
            field=models.ManyToManyField(null=True, to='blog.Blog'),
        ),
    ]
