# Generated by Django 3.0.8 on 2020-07-17 15:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portfolio', '0007_auto_20200717_2026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='writer',
            name='blog_written',
        ),
    ]
